#include <map>
#include "Utils/StringHelper.h"

namespace Utils {

const std::map<Common::NaluSeiPt_t, std::string> NaluSeiPtToStrMap = {
    { Common::NaluSeiPt_t::buffering_period                            , "buffering_period" },
    { Common::NaluSeiPt_t::picture_timing                              , "picture_timing" },
    { Common::NaluSeiPt_t::pain_scan_rect                              , "pain_scan_rect" },
    { Common::NaluSeiPt_t::filler_payload                              , "filler_payload" },
    { Common::NaluSeiPt_t::user_data_registered_itu_t_t35              , "user_data_registered_itu_t_t35" },
    { Common::NaluSeiPt_t::user_data_unregistered                      , "user_data_unregistered" },
    { Common::NaluSeiPt_t::recovery_point                              , "recovery_point" },
    { Common::NaluSeiPt_t::dec_ref_pic_marking_repetition              , "dec_ref_pic_marking_repetition" },
    { Common::NaluSeiPt_t::spare_pic                                   , "spare_pic" },
    { Common::NaluSeiPt_t::scene_info                                  , "scene_info" },
    { Common::NaluSeiPt_t::sub_seq_info                                , "sub_seq_info" },
    { Common::NaluSeiPt_t::sub_seq_layer_characteristics               , "sub_seq_layer_characteristics" },
    { Common::NaluSeiPt_t::sub_seq_characteristics                     , "sub_seq_characteristics" },
    { Common::NaluSeiPt_t::full_frame_freeze                           , "full_frame_freeze" },
    { Common::NaluSeiPt_t::full_frame_freeze_release                   , "full_frame_freeze_release" },
    { Common::NaluSeiPt_t::full_frame_snapshot                         , "full_frame_snapshot" },
    { Common::NaluSeiPt_t::progressive_refinement_segment_start        , "progressive_refinement_segment_start" },
    { Common::NaluSeiPt_t::progressive_refinement_segment_end          , "progressive_refinement_segment_end" },
    { Common::NaluSeiPt_t::motion_constrained_slice_group_set          , "motion_constrained_slice_group_set" },
    { Common::NaluSeiPt_t::film_grain_characteristics                  , "film_grain_characteristics" },
    { Common::NaluSeiPt_t::deblocking_filter_display_preference        , "deblocking_filter_display_preference" },
    { Common::NaluSeiPt_t::stereo_video_info                           , "stereo_video_info" },
    { Common::NaluSeiPt_t::post_filter_hint                            , "post_filter_hint" },
    { Common::NaluSeiPt_t::tone_mapping_info                           , "tone_mapping_info" },
    { Common::NaluSeiPt_t::scalability_info                            , "scalability_info" },
    { Common::NaluSeiPt_t::sub_pic_scalable_layers                     , "sub_pic_scalable_layers" },
    { Common::NaluSeiPt_t::non_required_layer_rep                      , "non_required_layer_rep" },
    { Common::NaluSeiPt_t::priority_layer_info                         , "priority_layer_info" },
    { Common::NaluSeiPt_t::layers_not_present                          , "layers_not_present" },
    { Common::NaluSeiPt_t::layer_dependency_change                     , "layer_dependency_change" },
    { Common::NaluSeiPt_t::scalable_nesting                            , "scalable_nesting" },
    { Common::NaluSeiPt_t::base_layer_temporal_hrd                     , "base_layer_temporal_hrd" },
    { Common::NaluSeiPt_t::quality_layer_integrity_check               , "quality_layer_integrity_check" },
    { Common::NaluSeiPt_t::redundant_pic_property                      , "redundant_pic_property" },
    { Common::NaluSeiPt_t::tl0_dep_rep_index                           , "tl0_dep_rep_index" },
    { Common::NaluSeiPt_t::tl_switching_point                          , "tl_switching_point" },
    { Common::NaluSeiPt_t::parallel_decoding_info                      , "parallel_decoding_info" },
    { Common::NaluSeiPt_t::mvc_scalable_nesting                        , "mvc_scalable_nesting" },
    { Common::NaluSeiPt_t::view_scalability_info                       , "view_scalability_info" },
    { Common::NaluSeiPt_t::multiple_view_scene_info                    , "multiple_view_scene_info" },
    { Common::NaluSeiPt_t::multiview_acquisition_info                  , "multiview_acquisition_info" },
    { Common::NaluSeiPt_t::non_required_view_components                , "non_required_view_components" },
    { Common::NaluSeiPt_t::view_dependency_change                      , "view_dependency_change" },
    { Common::NaluSeiPt_t::operation_points_not_present                , "operation_points_not_present" },
    { Common::NaluSeiPt_t::base_view_temporal_hrd                      , "base_view_temporal_hrd" },
    { Common::NaluSeiPt_t::frame_packing_arrangement                   , "frame_packing_arrangement" },
    { Common::NaluSeiPt_t::multiview_view_position                     , "multiview_view_position" },
    { Common::NaluSeiPt_t::display_orientation                         , "display_orientation" },
    { Common::NaluSeiPt_t::mvcd_scalable_nesting                       , "mvcd_scalable_nesting" },
    { Common::NaluSeiPt_t::mvcd_view_scalability_info                  , "mvcd_view_scalability_info" },
    { Common::NaluSeiPt_t::depth_representation_info                   , "depth_representation_info" },
    { Common::NaluSeiPt_t::three_dimensional_reference_displays_info   , "three_dimensional_reference_displays_info" },
    { Common::NaluSeiPt_t::depth_timing                                , "depth_timing" },
    { Common::NaluSeiPt_t::depth_sampling_info                         , "depth_sampling_info" },
    { Common::NaluSeiPt_t::constrained_depth_parameter_set_identifier  , "constrained_depth_parameter_set_identifier" },
    { Common::NaluSeiPt_t::green_metadata                              , "green_metadata" },
    { Common::NaluSeiPt_t::mastering_display_colour_volume             , "mastering_display_colour_volume" },
    { Common::NaluSeiPt_t::colour_remapping_info                       , "colour_remapping_info" },
    { Common::NaluSeiPt_t::content_light_level_info                    , "content_light_level_info" },
    { Common::NaluSeiPt_t::alternative_transfer_characteristics        , "alternative_transfer_characteristics" },
    { Common::NaluSeiPt_t::ambient_viewing_environment                 , "ambient_viewing_environment" },
    { Common::NaluSeiPt_t::content_colour_volume                       , "content_colour_volume" },
    { Common::NaluSeiPt_t::equirectangular_projection                  , "equirectangular_projection" },
    { Common::NaluSeiPt_t::cubemap_projection                          , "cubemap_projection" },
    { Common::NaluSeiPt_t::sphere_rotation                             , "sphere_rotation" },
    { Common::NaluSeiPt_t::regionwise_packing                          , "regionwise_packing" },
    { Common::NaluSeiPt_t::omni_viewport                               , "omni_viewport" },
    { Common::NaluSeiPt_t::alternative_depth_info                      , "alternative_depth_info" },
    { Common::NaluSeiPt_t::sei_manifestation                           , "sei_manifestation" },
    { Common::NaluSeiPt_t::sei_prefix_indication                       , "sei_prefix_indication" },
    { Common::NaluSeiPt_t::annotated_regions                           , "annotated_regions" },
    { Common::NaluSeiPt_t::shutter_interval_info                       , "shutter_interval_info" },
    { Common::NaluSeiPt_t::nn_post_filter_characteristics              , "nn_post_filter_characteristics" },
    { Common::NaluSeiPt_t::nn_post_filter_activation                   , "nn_post_filter_activation" },
    { Common::NaluSeiPt_t::phase_indication                            , "phase_indication" },
    { Common::NaluSeiPt_t::reserved_sei_message                        , "reserved_sei_message" },
};

const std::map<std::string, Common::NaluSeiPt_t> NaluSeiStrToPtMap = {
    { "buffering_period"                            , Common::NaluSeiPt_t::buffering_period                },
    { "picture_timing"                              , Common::NaluSeiPt_t::picture_timing                  },
    { "pain_scan_rect"                              , Common::NaluSeiPt_t::pain_scan_rect                  },
    { "filler_payload"                              , Common::NaluSeiPt_t::filler_payload                  },
    { "user_data_registered_itu_t_t35"              , Common::NaluSeiPt_t::user_data_registered_itu_t_t35  },
    { "user_data_unregistered"                      , Common::NaluSeiPt_t::user_data_unregistered          },
    { "recovery_point"                              , Common::NaluSeiPt_t::recovery_point                  },
    { "dec_ref_pic_marking_repetition"              , Common::NaluSeiPt_t::dec_ref_pic_marking_repetition  },
    { "spare_pic"                                   , Common::NaluSeiPt_t::spare_pic                       },
    { "scene_info"                                  , Common::NaluSeiPt_t::scene_info                      },
    { "sub_seq_info"                                , Common::NaluSeiPt_t::sub_seq_info                    },
    { "sub_seq_layer_characteristics"               , Common::NaluSeiPt_t::sub_seq_layer_characteristics   },
    { "sub_seq_characteristics"                     , Common::NaluSeiPt_t::sub_seq_characteristics         },
    { "full_frame_freeze"                           , Common::NaluSeiPt_t::full_frame_freeze               },
    { "full_frame_freeze_release"                   , Common::NaluSeiPt_t::full_frame_freeze_release       },
    { "full_frame_snapshot"                         , Common::NaluSeiPt_t::full_frame_snapshot             },
    { "progressive_refinement_segment_start"        , Common::NaluSeiPt_t::progressive_refinement_segment_start },
    { "progressive_refinement_segment_end"          , Common::NaluSeiPt_t::progressive_refinement_segment_end   },
    { "motion_constrained_slice_group_set"          , Common::NaluSeiPt_t::motion_constrained_slice_group_set   },
    { "film_grain_characteristics"                  , Common::NaluSeiPt_t::film_grain_characteristics           },
    { "deblocking_filter_display_preference"        , Common::NaluSeiPt_t::deblocking_filter_display_preference },
    { "stereo_video_info"                           , Common::NaluSeiPt_t::stereo_video_info                    },
    { "post_filter_hint"                            , Common::NaluSeiPt_t::post_filter_hint                     },
    { "tone_mapping_info"                           , Common::NaluSeiPt_t::tone_mapping_info                    },
    { "scalability_info"                            , Common::NaluSeiPt_t::scalability_info                     },
    { "sub_pic_scalable_layers"                     , Common::NaluSeiPt_t::sub_pic_scalable_layers              },
    { "non_required_layer_rep"                      , Common::NaluSeiPt_t::non_required_layer_rep               },
    { "priority_layer_info"                         , Common::NaluSeiPt_t::priority_layer_info                  },
    { "layers_not_present"                          , Common::NaluSeiPt_t::layers_not_present                   },
    { "layer_dependency_change"                     , Common::NaluSeiPt_t::layer_dependency_change              },
    { "scalable_nesting"                            , Common::NaluSeiPt_t::scalable_nesting                     },
    { "base_layer_temporal_hrd"                     , Common::NaluSeiPt_t::base_layer_temporal_hrd              },
    { "quality_layer_integrity_check"               , Common::NaluSeiPt_t::quality_layer_integrity_check        },
    { "redundant_pic_property"                      , Common::NaluSeiPt_t::redundant_pic_property               },
    { "tl0_dep_rep_index"                           , Common::NaluSeiPt_t::tl0_dep_rep_index                    },
    { "tl_switching_point"                          , Common::NaluSeiPt_t::tl_switching_point                   },
    { "parallel_decoding_info"                      , Common::NaluSeiPt_t::parallel_decoding_info               },
    { "mvc_scalable_nesting"                        , Common::NaluSeiPt_t::mvc_scalable_nesting                       },
    { "view_scalability_info"                       , Common::NaluSeiPt_t::view_scalability_info                      },
    { "multiple_view_scene_info"                    , Common::NaluSeiPt_t::multiple_view_scene_info                   },
    { "multiview_acquisition_info"                  , Common::NaluSeiPt_t::multiview_acquisition_info                 },
    { "non_required_view_components"                , Common::NaluSeiPt_t::non_required_view_components               },
    { "view_dependency_change"                      , Common::NaluSeiPt_t::view_dependency_change                     },
    { "operation_points_not_present"                , Common::NaluSeiPt_t::operation_points_not_present               },
    { "base_view_temporal_hrd"                      , Common::NaluSeiPt_t::base_view_temporal_hrd                     },
    { "frame_packing_arrangement"                   , Common::NaluSeiPt_t::frame_packing_arrangement                  },
    { "multiview_view_position"                     , Common::NaluSeiPt_t::multiview_view_position                    },
    { "display_orientation"                         , Common::NaluSeiPt_t::display_orientation                        },
    { "mvcd_scalable_nesting"                       , Common::NaluSeiPt_t::mvcd_scalable_nesting                      },
    { "mvcd_view_scalability_info"                  , Common::NaluSeiPt_t::mvcd_view_scalability_info                 },
    { "depth_representation_info"                   , Common::NaluSeiPt_t::depth_representation_info                  },
    { "three_dimensional_reference_displays_info"   , Common::NaluSeiPt_t::three_dimensional_reference_displays_info  },
    { "depth_timing"                                , Common::NaluSeiPt_t::depth_timing                               },
    { "depth_sampling_info"                         , Common::NaluSeiPt_t::depth_sampling_info                        },
    { "constrained_depth_parameter_set_identifier"  , Common::NaluSeiPt_t::constrained_depth_parameter_set_identifier },
    { "green_metadata"                              , Common::NaluSeiPt_t::green_metadata                             },
    { "mastering_display_colour_volume"             , Common::NaluSeiPt_t::mastering_display_colour_volume      },
    { "colour_remapping_info"                       , Common::NaluSeiPt_t::colour_remapping_info                },
    { "content_light_level_info"                    , Common::NaluSeiPt_t::content_light_level_info             },
    { "alternative_transfer_characteristics"        , Common::NaluSeiPt_t::alternative_transfer_characteristics },
    { "ambient_viewing_environment"                 , Common::NaluSeiPt_t::ambient_viewing_environment          },
    { "content_colour_volume"                       , Common::NaluSeiPt_t::content_colour_volume                },
    { "equirectangular_projection"                  , Common::NaluSeiPt_t::equirectangular_projection           },
    { "cubemap_projection"                          , Common::NaluSeiPt_t::cubemap_projection                   },
    { "sphere_rotation"                             , Common::NaluSeiPt_t::sphere_rotation                      },
    { "regionwise_packing"                          , Common::NaluSeiPt_t::regionwise_packing                   },
    { "omni_viewport"                               , Common::NaluSeiPt_t::omni_viewport                        },
    { "alternative_depth_info"                      , Common::NaluSeiPt_t::alternative_depth_info               },
    { "sei_manifestation"                           , Common::NaluSeiPt_t::sei_manifestation                    },
    { "sei_prefix_indication"                       , Common::NaluSeiPt_t::sei_prefix_indication                },
    { "annotated_regions"                           , Common::NaluSeiPt_t::annotated_regions                    },
    { "shutter_interval_info"                       , Common::NaluSeiPt_t::shutter_interval_info                },
    { "nn_post_filter_characteristics"              , Common::NaluSeiPt_t::nn_post_filter_characteristics       },
    { "nn_post_filter_activation"                   , Common::NaluSeiPt_t::nn_post_filter_activation            },
    { "phase_indication"                            , Common::NaluSeiPt_t::phase_indication                     },
    { "reserved_sei_message"                        , Common::NaluSeiPt_t::reserved_sei_message                 },
};

std::string StringHelper::NaluSeiPtToStr(Common::NaluSeiPt_t pt) {
    auto iter = NaluSeiPtToStrMap.find(pt);
    return NaluSeiPtToStrMap.end() == iter ? "reserved_sei_message" : iter->second;
}

Common::NaluSeiPt_t StringHelper::NaluSeiStrToPt(const std::string& str) {
    auto iter = NaluSeiStrToPtMap.find(str);
    return NaluSeiStrToPtMap.end() == iter ? Common::NaluSeiPt_t::reserved_sei_message : iter->second;
}

} // namespace Utils